In [1]:
import argparse
import os
from functools import partial

import einops
import numpy as np
import pandas as pd
import torch
import torch.nn.functional as F
import tqdm
from huggingface_hub import hf_hub_download
from transformer_lens import HookedTransformer, utils

from attn_sae import *
from sae_training.sae_group import SAEGroup
from sae_training.utils import LMSparseAutoencoderSessionloader

from e2e_sae import SAETransformer
import random 

import sys
sys.path.append("../scripts")
from error_eval import cos_sim, load_sae, load_attn_sae
# from feature_extrapolation import feature_extrapolation, create_ablation_hooks, run_all_ablations, get_alive_features, run_error_eval_experiment

from sensitive_direction import get_all_activations, create_ablation_hooks, run_all_ablations

In [3]:
random_uniform = np.random.uniform(low = 0.0, high = 1.0, size = (5, 10))

In [5]:
(random_uniform * 10).astype(int)

array([[6, 0, 0, 6, 3, 5, 6, 0, 5, 4],
       [8, 7, 6, 2, 2, 3, 4, 3, 3, 7],
       [6, 5, 3, 7, 1, 0, 3, 6, 5, 7],
       [5, 1, 3, 3, 1, 0, 1, 0, 7, 2],
       [0, 0, 7, 1, 1, 4, 5, 0, 1, 5]])

## functions

In [13]:
def towards_a_vector(activation, hook, to_vector, length, pos=None):
    new_direction = (to_vector - activation)
    new_direction_unit_vector = new_direction/new_direction.norm(dim=-1, keepdim=True)
    perturbed_activation = activation + new_direction_unit_vector * length

    if pos is None:
        activation[:] = perturbed_activation
    else:
        activation[:, pos] = perturbed_activation[:, pos]    
    return activation

def create_ablation_hooks(direction_type, device, activations_shape, pos= None, multiNormal = None, all_activations = None, length_ranges="Normal"):
    ablation_hooks = []

    if length_ranges == "Normal":
        length_list = list(range(1, 20, 2)) + list(range(20, 50, 4)) + list(range(51, 211, 10))
    elif length_ranges == "Short":
        length_list = list(range(1, 30))
        length_list = [x/10 for x in length_list]
    
    if direction_type == "naive_random":
        to_vector = torch.randn(activations_shape).to(device)      
    elif direction_type == "cov_random":
        to_vector = multiNormal.sample(sample_shape = [activations_shape[0], activations_shape[1]]).to(device)
    elif direction_type == "real_direction":
        tensor_length = all_activations.shape[0]
        
        activation_num = activations_shape[0] * activations_shape[1] # get number of activations to sample
        random_indexes = torch.randperm(tensor_length)[:activation_num]
        print(random_indexes)
        to_vector = all_activations[random_indexes,:]
        print(to_vector)
        to_vector = einops.rearrange(to_vector, "(batch seq) n_hidden -> batch seq n_hidden", batch = activations_shape[0])

    
    for length in length_list:
        ablation_hooks.append((f'length_{length}', 
                               partial(towards_a_vector, to_vector = to_vector, length = length, pos=pos)))
    
    # elif direction_type == "cov_random":
    #     to_vector = multiNormal.sample(sample_shape = [activations_shape[0], activations_shape[1]]).to(device)
    #     for length in length_list:
    #         ablation_hooks.append((f'length_{length}', 
    #                                partial(towards_a_vector, to_vector = to_vector, length = length,
    #                                        pos=pos)))
    # elif direction_type == "real_direction":
    #     tensor_length = all_activations.shape[0]
    #     random_index = random.sample(range(tensor_length), 1)
    #     to_vector = token_tensor[random_index,:]
    #     for length in length_list:
    #         ablation_hooks.append((f'length_{length}', 
    #                                partial(towards_a_vector, to_vector = to_vector, length = length, pos=pos)))

    return ablation_hooks

# load stuff

In [2]:
device = "cpu"

model_id = "h9hrelni"
text = "sparsify/gpt2/" + model_id
sae_transformer_model = SAETransformer.from_wandb(text)

model = sae_transformer_model.tlens_model
sae = sae_transformer_model.saes[f"blocks-6-hook_resid_pre"]

sae = sae.to(device)
model = model.to(device)

seed = 23
# set seed
random.seed(seed)
torch.manual_seed(seed)

token_tensor = torch.load("../token_tensor.pt").to(device)
token_tensor_small = token_tensor[:100,:]

layer = 6
hook_loc = "resid_pre"
e2e = model_id
pos = None
batch_size = 64
activation_loc = utils.get_act_name(hook_loc, layer)

Loaded pretrained model gpt2-small into HookedTransformer
Moving model to device:  cpu


In [22]:
token_tensor.shape[0] * token_tensor.shape[1]

2048000

In [3]:
token_tensor_small = token_tensor[:100,:]


In [10]:
direction_type = "real_direction"
remove_first_token = True
length_ranges = "Normal"

In [7]:
dataloader = torch.utils.data.DataLoader(
    token_tensor_small,
    batch_size=2,
    shuffle=False
)

activation_loc = utils.get_act_name(hook_loc, layer)

if direction_type != "naive_random":
    all_activations = get_all_activations(dataloader, model, activation_loc, e2e, remove_first_token)

    if direction_type == "cov_random":
        covariance = torch.cov(all_activations.T)
        torch.save(covariance, 'covariance.pt')
        mean = torch.mean(all_activations.T, dim = 1)

        # add a small value to ensure positive definite
        cov = covariance.clone()
        mask = cov.diagonal()
        cov += torch.diag(mask).bool().float() * 0.01
        
        multiNormal = torch.distributions.multivariate_normal.MultivariateNormal(mean.to("cpu"), cov.to("cpu"))
        del all_activations
        
    if direction_type == "real_direction":
        tensor_length = all_activations.shape[0]
        random_indexes = torch.randperm(tensor_length)[:100] # sample 500,000 vectors for memory purposes
        sampled_activations = all_activations[random_indexes,:]            

result_dfs = []
for ix, batch_tokens in enumerate(tqdm.tqdm(dataloader)):
    with torch.inference_mode():
        _, cache = model.run_with_cache(
            batch_tokens, 
            prepend_bos=True,
            names_filter=[activation_loc]
        )
        activations = cache[activation_loc]
        if hook_loc == "z":
            activations = einops.rearrange(
                activations, "batch seq n_heads d_head -> batch seq (n_heads d_head)",
            )
        

        if direction_type == "naive_random":
            ablation_hooks = create_ablation_hooks(direction_type=direction_type,  activations_shape = activations.shape, 
                                               device=device, pos=pos, length_ranges=length_ranges)
        elif direction_type == "cov_random":
            ablation_hooks = create_ablation_hooks(direction_type=direction_type, activations_shape = activations.shape, 
                                                   device=device, pos=pos,
                                                   multiNormal=multiNormal, length_ranges=length_ranges)
        elif direction_type == "real_direction":
            ablation_hooks = create_ablation_hooks(direction_type=direction_type, activations_shape = activations.shape, 
                                                   device=device, pos=pos,
                                                   all_activations=sampled_activations, length_ranges=length_ranges)
        
        if hook_loc == "z":
            ablation_hooks = [
                (name, partial(attn_hook_wrapper, hook_fn=hook_fn))
                for name, hook_fn in ablation_hooks
            ]
        
        batch_result_df = run_all_ablations(model, batch_tokens, ablation_hooks, layer=layer, hook_loc=hook_loc, device=device)
        
        # l0 = (feature_acts > 0).float().sum(dim=-1).cpu().numpy()[:, :-1].flatten()
        # l1 = feature_acts.abs().sum(dim=-1).cpu().numpy()[:, :-1].flatten()
        # reconstruction_error = (activations - sae_out).norm(dim=-1).cpu().numpy()[:, :-1].flatten()
        
        batch_result_df['norm'] = activations.norm(dim=-1).cpu().numpy()[:, :-1].flatten()
        # batch_result_df['cos'] = cos_sim(activations, sae_out).cpu().numpy()[:, :-1].flatten()
        
        result_dfs.append(batch_result_df)

        break

  0%|                                                                                                                                                               | 0/50 [00:01<?, ?it/s]


NameError: name 'length_ranges' is not defined

In [14]:
ablation_hooks = create_ablation_hooks(direction_type=direction_type, activations_shape = activations.shape, 
                                                   device=device, pos=pos,
                                                   all_activations=sampled_activations, length_ranges=length_ranges)

tensor([50, 58,  2, 71, 45, 98, 64, 38, 70,  8, 40, 13,  1, 90, 23, 95, 57, 67,
        41, 81, 65, 63, 96, 19, 72, 84, 75, 25, 44,  6, 88, 48, 56, 35, 66, 52,
        86, 16, 94, 20, 49, 62,  5, 18, 60, 85, 24, 78, 79, 33,  7, 37, 10, 15,
        80, 11, 46, 22, 14, 21, 47, 53, 83, 55,  4, 12, 77,  0, 59, 76, 91, 39,
        92, 69, 73, 36, 61, 31, 99, 26, 17, 51,  9, 89, 74, 30, 87, 68, 82, 27,
        97, 42, 32, 28, 34,  3, 43, 29, 54, 93])
tensor([[ 3.5101,  1.7147, -0.6312,  ...,  0.3367,  1.7955,  1.7436],
        [-1.1849,  2.7385,  0.9204,  ...,  2.1008,  0.3449,  0.2882],
        [ 0.8778,  0.7167, -4.9561,  ...,  0.3903,  0.8325,  1.3789],
        ...,
        [-1.6380, -0.1311, -0.5860,  ..., -0.6948, -1.0683, -0.2162],
        [ 1.5599,  1.4908, -0.3123,  ...,  0.6582,  1.5702,  1.6883],
        [-0.7571,  0.0691,  3.1953,  ..., -0.4467,  4.0190,  1.5421]])


In [19]:
sampled_activations[2,:]

tensor([ 8.7778e-01,  7.1674e-01, -4.9561e+00, -4.4034e+00, -6.0469e-01,
        -3.0892e+00,  2.8137e+00,  5.0061e-01,  2.1039e+00, -3.4933e+00,
         5.9400e+00, -1.0287e+00,  1.2081e+00,  2.8749e+00, -4.5856e+00,
         6.3905e+00,  2.6838e+00,  2.7022e+00,  1.1417e+00, -4.5147e+00,
        -1.7885e+00,  1.8145e+00,  1.1262e-01, -3.4556e+00,  5.7459e-01,
        -6.1438e-01,  3.3012e-01, -1.9292e+00, -7.0629e-01,  1.8154e+00,
        -3.6805e+00,  4.2067e-01,  1.0885e-01, -5.9192e-01, -2.4495e+00,
         5.4465e+00,  1.9291e+00, -1.2806e+00, -4.3543e-01, -4.0242e+00,
        -7.4952e-02, -2.6162e+00,  1.4660e+00, -2.4671e+00,  8.6444e-01,
         1.4405e-01, -1.6898e+00, -6.8898e-01,  4.2748e+00,  2.3710e+00,
        -1.0327e+00, -1.7839e+00,  1.8941e+00,  2.8372e+00, -4.1695e+00,
         1.5422e+00,  9.0718e-03,  1.5927e+00, -2.0789e+00, -2.6660e+00,
         3.8512e-01, -7.3037e-01, -1.5405e+00,  2.8936e+00, -3.0933e+01,
         1.5688e+00, -1.3720e+00,  3.0233e+00, -5.5